locale: "en-US"
description: "Studies on knowledge and information management, digital libraries and open science"

author:
  bio: "Studies on knowledge and information management, digital libraries and open science."
  location: "Istanbul, Turkey"
  employer: "Republic of Türkiye Ministry of Culture and Tourism, Rami Library"
